### PR TITLE
create-string-match.cpp

### PR DESCRIPTION
**Pull request by sarthakdelori**

### CODE REVIEW

**Comment by dsnehasish74** [comment]
The Repository structure is Changed Please Submit your code under respective language

**Comment by sarthakdelori** [comment]
Updated the location of file according to the structure.

**Comment by sarthakdelori** [comment]
Do add the Hacktoberfest and Hacktoberfest-accepted label while merging.

**Comment by sarthakdelori** [comment]
Your project is not participating in hacktoberfest? It's showing on my hacktoberfest profile.

**Pull request merged**
